default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: famcart_development

test:
  <<: *default
  database: famcart_test

production:
  adapter: postgresql
  host: famcart webservice
  port: 5432
  database: famcart
  username: famcart_user
  password: your_password_here
